### ISSUE TITLE
More ergonomic labels with C-strings?

### ISSUE THREAD

**Issue by oleganza** [hdevalence/libmerlin#7]
In Rust implementation the labels are byte slices `&[u8]` and most of the time they are defined with ASCII literals `b"label"`. This is not possible in C: we either allow arbitrary byte slices with explicit length argument, or we could use C strings (0-terminated) and restrict the C API to not use 0x00 in the labels.

WDYT?

**Comment by hdevalence** [comment]
I'm a bit worried about allowing null-terminated strings because null-terminated strings are dangerous, and also because it means that the capability of the API doesn't overlap with the capability of the Rust API.

The Rust API is a little more restrictive, as it requires that the labels are `&'static [u8]`, enforcing that the labels are supposed to be static constants (because they are the protocol framing). There's not really a good way to express this in C, so the C API currently has a superset of capabilities compared to the Rust one (you can express anything that's possible to express using the Rust API, but you can also do something invalid by using non-`&'static` labels).  If the C API used null-terminated byte strings, this would make the capabilities not a strict superset, but something different (since you could not use null bytes in labels), which makes me uneasy.

Alternatively, it would also be possible to make a convenience API that took null-terminated byte arrays, but then there are two sets of functions so the API is much more complicated.

Ideally, this won't be a big issue, because the labels in C programs should be declared as constants, so that calling some function looks like
```
commit_bytes(ctx, SOME_LABEL, SOME_LABEL_LEN, ...);
```
and I think that's reasonable.

**Comment by oleganza** [comment]
I was about to suggest to restrict labels in Rust API to ASCII/UTF8 labels. E.g. `&str` instead of `&[u8]`. But 0x00 is allowed in UTF8 and that still wouldn't work.

I agree with your rationale.
